UpdatePowerDelay: 120
PowerLore: '&c&l҉ &fTổng Lực chiến &e%power%'
TopMessageFormat: '&e&lTOP&4&l %position%&7- &a%name% &7- &e%power%'
PlayerPower: '&fLực chiến của bạn &e%power%&7 - &4&lTOP &c#%position%'
AEEnchantmentPower:
  lightning: 100
  lifesteal: 300
VanillaEnchantmentPower:
  ARROW_DAMAGE: 9
  DIG_SPEED: 9
  ARROW_FIRE: 9
  ARROW_INFINITE: 9
  ARROW_KNOCKBACK: 9
  BINDING_CURSE: 1
  DAMAGE_ALL: 9
  DAMAGE_ARTHROPODS: 9
  DAMAGE_UNDEAD: 9
  DEPTH_STRIDER: 9
  DURABILITY: 9
  FIRE_ASPECT: 9
  FROST_WALKER: 9
  KNOCKBACK: 9
  LOOT_BONUS_BLOCKS: 9
  LOOT_BONUS_MOBS: 9
  LUCK: 9
  LURE: 9
  MENDING: 9
  OXYGEN: 9
  PROTECTION_ENVIRONMENTAL: 9
  PROTECTION_EXPLOSIONS: 9
  PROTECTION_FALL: 9
  PROTECTION_FIRE: 9
  PROTECTION_PROJECTILE: 9
  SILK_TOUCH: 9
  SWEEPING_EDGE: 9
  THORNS: 9
  VANISHING_CURSE: 1
  WATER_WORKER: 9
MyItemAttributePower:
  DAMAGE: 2
  CRITICAL_CHANCE: 2
  CRITICAL_DAMAGE: 200
  PENETRATION: 10
  PVP_DAMAGE: 2
  PVE_DAMAGE: 2
  DEFENSE: 2
  PVP_DEFENSE: 2
  PVE_DEFENSE: 2
  HEALTH: 2
  HEALTH_REGEN: 2
  STAMINA_MAX: 2
  STAMINA_REGEN: 2
  ATTACK_AOE_RADIUS: 2
  ATTACK_AOE_DAMAGE: 2
  BLOCK_AMOUNT: 2
  BLOCK_RATE: 2
  HIT_RATE: 2
  DODGE_RATE: 2
  FISHING_CHANCE: 2
  FISHING_POWER: 2
  FISHING_SPEED: 2
  LURES_MAX_TENSION: 2
  LURES_ENDURANCE: 2
  DURABILITY: 2
  LEVEL: 100
MyItemSocketPower:
  ADDITIONAL_DAMAGE: 10
  PERCENT_DAMAGE: 10
  PENETRATION: 10
  PVP_DAMAGE: 10
  PVE_DAMAGE: 10
  ADDITIONAL_DEFENSE: 10
  PERCENT_DEFENSE: 10
  HEALTH: 10
  PVP_DEFENSE: 10
  PVE_DEFENSE: 10
  CRITICAL_CHANCE: 10
  CRITICAL_DAMAGE: 10
  BLOCK_AMOUNT: 10
  BLOCK_RATE: 10
  HIT_RATE: 10
  DODGE_RATE: 10
